<a href="https://colab.research.google.com/github/batrataj/NEXUS-SEC/blob/main/notebooks/1_data_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/batrataj/NEXUS-SEC/main/Wednesday-workingHours.pcap_ISCX.xlsx"

df = pd.read_excel(url)

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Label
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,BENIGN
1,389,479,11,5,172,326,79,0,15.636364,31.449238,BENIGN
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,BENIGN
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,BENIGN
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,BENIGN

In [3]:
df.shape

(999, 11)

In [4]:
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', ' Label'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0    Destination Port             999 non-null    int64
 1    Flow Duration                999 non-null    int64
 2    Total Fwd Packets            999 non-null    int64
 3    Total Backward Packets       999 non-null    int64
 4   Total Length of Fwd Packets   999 non-null    int64
 5    Total Length of Bwd Packets  999 non-null    int64
 6    Fwd Packet Length Max        999 non-null    int64
 7    Fwd Packet Length Min        999 non-null    int64
 8    Fwd Packet Length Mean       999 non-null    float64
 9    Fwd Packet Length Std        999 non-null    float64
 10   Label                        999 non-null    object
dtypes: float64(2), int64(8), object(1)
memory usage: 86.0+ KB

In [6]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std
count,999.000000,9.990000e+02,999.000000,999.000000,9.990000e+02,9.990000e+02,999.000000,999.000000,999.000000,999.000000
mean,5767.329329,3.206594e+07,407.340340,516.609610,5.370683e+03,1.134357e+06,618.138138,12.002002,118.819105,177.081523
std,14412.264809,4.219467e+07,8620.770141,11067.475445,5.401283e+04,2.464551e+07,2215.422788,27.134490,372.777500,511.583145
min,0.000000,1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,80.000000,1.013100e+04,2.000000,1.000000,3.850000e+01,6.000000e+00,31.000000,0.000000,14.333333,0.000000
50%,135.000000,5.257736e+06,7.000000,4.000000,3.540000e+02,2.250000e+02,158.000000,0.000000,48.000000,44.375669
75%,443.000000,6.604197e+07,14.000000,10.000000,9.680000e+02,3.974000e+03,415.000000,6.000000,70.765766,121.276936
max,59970.000000,1.199999e+08,203943.000000,263412.000000,1.224076e+06,5.840000e+08,24820.000000,235.000000,4640.757576,6429.190773

In [11]:
df[' Label'].value_counts()

 Label
BENIGN    999
Name: count, dtype: int64