<a href="https://colab.research.google.com/github/batrataj/NEXUS-SEC/blob/main/notebooks/2_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/batrataj/NEXUS-SEC/main/Wednesday-workingHours.pcap_ISCX.xlsx"

df = pd.read_excel(url)

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Label
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,BENIGN
1,389,479,11,5,172,326,79,0,15.636364,31.449238,BENIGN
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,BENIGN
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,BENIGN
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,BENIGN

In [3]:
df.columns = df.columns.str.strip()

In [4]:
df.isnull().sum()

Destination Port               0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Fwd Packet Length Max          0
Fwd Packet Length Min          0
Fwd Packet Length Mean         0
Fwd Packet Length Std          0
Label                          0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.duplicated().sum()

np.int64(7)

In [7]:
df = df.drop_duplicates()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 992 entries, 0 to 998
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Destination Port             992 non-null    int64
 1   Flow Duration                992 non-null    int64
 2   Total Fwd Packets            992 non-null    int64
 3   Total Backward Packets       992 non-null    int64
 4   Total Length of Fwd Packets  992 non-null    int64
 5   Total Length of Bwd Packets  992 non-null    int64
 6   Fwd Packet Length Max        992 non-null    int64
 7   Fwd Packet Length Min        992 non-null    int64
 8   Fwd Packet Length Mean       992 non-null    float64
 9   Fwd Packet Length Std        992 non-null    float64
 10  Label                        992 non-null    object
dtypes: float64(2), int64(8), object(1)
memory usage: 93.0+ KB

In [9]:
df['Label'].value_counts()

Label
BENIGN    992
Name: count, dtype: int64

In [11]:
df.to_csv("clean_network_data.xlsx", index=False)